In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report

In [2]:
columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

In [3]:
df = pd.read_csv('iris.csv',names=columns)

In [4]:
df.sample(10)

     sepal_length  sepal_width  petal_length  petal_width          species
3             4.6          3.1           1.5          0.2      Iris-setosa
129           7.2          3.0           5.8          1.6   Iris-virginica
18            5.7          3.8           1.7          0.3      Iris-setosa
135           7.7          3.0           6.1          2.3   Iris-virginica
140           6.7          3.1           5.6          2.4   Iris-virginica
54            6.5          2.8           4.6          1.5  Iris-versicolor
50            7.0          3.2           4.7          1.4  Iris-versicolor
65            6.7          3.1           4.4          1.4  Iris-versicolor
117           7.7          3.8           6.7          2.2   Iris-virginica
2             4.7          3.2           1.3          0.2      Iris-setosa

In [5]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [6]:
le= LabelEncoder()

In [15]:
x = df.iloc[:,:-1]

In [17]:
y= df.iloc[:,-1]

In [19]:
y_encoded = le.fit_transform(y)

In [21]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,train_size=0.7,random_state=42)

In [23]:
xtrain

     sepal_length  sepal_width  petal_length  petal_width
81            5.5          2.4           3.7          1.0
133           6.3          2.8           5.1          1.5
137           6.4          3.1           5.5          1.8
75            6.6          3.0           4.4          1.4
109           7.2          3.6           6.1          2.5
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[105 rows x 4 columns]

In [25]:
from sklearn.linear_model import LogisticRegression

In [27]:
LR = LogisticRegression(max_iter=200)

In [29]:
LR.fit(xtrain,ytrain)

LogisticRegression(max_iter=200)

In [31]:
y_pred = LR.predict(xtest)

In [33]:
print("Accuracy:",accuracy_score(y_pred,ytest))
print("Confusion Matrix:\n", confusion_matrix(y_pred,ytest))
print("Classification Report:\n", classification_report(y_pred,ytest))

Accuracy: 1.0
Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00        13

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45

In [35]:
import pickle

In [37]:
filename = 'trained_model.sav'
pickle.dump(LR,open(filename,'wb'))

In [39]:
loadmodel = pickle.load(open('trained_model.sav','rb'))

In [41]:
input_data = pd.DataFrame([[5.8, 2.7, 5.1, 1.9]], 
                          columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])

# Make prediction
prediction = loadmodel.predict(input_data)

# Display result
print("\nPredicted species for input", input_data.values.tolist(), "is:", prediction[0])

Predicted species for input [[5.8, 2.7, 5.1, 1.9]] is: Iris-virginica

In [ ]:
with open(r'D:\datasets\label_encoder.sav', 'wb') as f:
    pickle.dump(label_encoder, f)