In [1]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('bank-additional-full.csv',sep=';')
df.sample(10)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
27324,47,admin.,married,university.degree,no,yes,no,cellular,nov,fri,...,1,999,1,failure,-0.1,93.200,-42.0,4.021,5195.8,no
19053,51,technician,divorced,high.school,unknown,no,no,cellular,aug,tue,...,3,999,0,nonexistent,1.4,93.444,-36.1,4.968,5228.1,no
6032,43,management,married,basic.4y,no,yes,no,telephone,may,tue,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
15380,46,blue-collar,married,basic.4y,unknown,no,no,cellular,jul,fri,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.957,5228.1,no
17138,34,technician,married,university.degree,no,yes,no,cellular,jul,fri,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
13024,31,admin.,single,high.school,no,no,no,cellular,jul,tue,...,35,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
23551,46,technician,married,professional.course,no,no,no,cellular,aug,thu,...,2,999,0,nonexistent,1.4,93.444,-36.1,4.962,5228.1,no
5405,46,blue-collar,married,basic.9y,unknown,no,no,telephone,may,fri,...,10,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
38518,81,housemaid,married,basic.4y,no,yes,no,cellular,oct,wed,...,2,999,0,nonexistent,-3.4,92.431,-26.9,0.724,5017.5,no
28522,23,technician,single,professional.course,no,no,yes,cellular,apr,tue,...,4,999,0,nonexistent,-1.8,93.075,-47.1,1.423,5099.1,no

In [3]:
x = df.iloc[:,[1,3]]

In [4]:
y = df.iloc[:,-1]

In [5]:
xtrain , xtest, ytrain , ytest = train_test_split(x,y,test_size=0.75, random_state=42)

In [6]:
xtrain

               job            education
24468       admin.    university.degree
26091       admin.    university.degree
21143   technician  professional.course
9551        admin.             basic.9y
28084  blue-collar             basic.9y
...            ...                  ...
6265       retired  professional.course
11284   management    university.degree
38158       admin.          high.school
860     management    university.degree
15795       admin.    university.degree

[10297 rows x 2 columns]

In [7]:
ytrain

24468     no
26091     no
21143     no
9551      no
28084     no
        ...
6265      no
11284     no
38158    yes
860       no
15795     no
Name: y, Length: 10297, dtype: object

In [8]:
df.value_counts('job')

job
admin.           10422
blue-collar       9254
technician        6743
services          3969
management        2924
retired           1720
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
unknown            330
Name: count, dtype: int64

In [9]:
df.value_counts('y')

y
no     36548
yes     4640
Name: count, dtype: int64

In [10]:
df.value_counts('education')

education
university.degree      12168
high.school             9515
basic.9y                6045
professional.course     5243
basic.4y                4176
basic.6y                2292
unknown                 1731
illiterate                18
Name: count, dtype: int64

In [11]:
od  = OrdinalEncoder(categories=[["management","admin.","technician","entrepreneur","self-employed","blue-collar","services","housemaid","retired","unemployed","student","unknown"],
['university.degree','professional.course','high.school','basic.9y','basic.6y','basic.4y','unknown','illiterate']])

In [12]:
od.fit(xtrain)

OrdinalEncoder(categories=[['management', 'admin.', 'technician',
                            'entrepreneur', 'self-employed', 'blue-collar',
                            'services', 'housemaid', 'retired', 'unemployed',
                            'student', 'unknown'],
                           ['university.degree', 'professional.course',
                            'high.school', 'basic.9y', 'basic.6y', 'basic.4y',
                            'unknown', 'illiterate']])

In [13]:
xtrain = od.transform(xtrain)
xtest = od.transform(xtest)

In [14]:
xtrain

array([[1., 0.],
       [1., 0.],
       [2., 1.],
       ...,
       [1., 2.],
       [0., 0.],
       [1., 0.]])

In [15]:
od.categories_

[array(['management', 'admin.', 'technician', 'entrepreneur',
        'self-employed', 'blue-collar', 'services', 'housemaid', 'retired',
        'unemployed', 'student', 'unknown'], dtype=object),
 array(['university.degree', 'professional.course', 'high.school',
        'basic.9y', 'basic.6y', 'basic.4y', 'unknown', 'illiterate'],
       dtype=object)]

In [16]:
leb = LabelEncoder()
leb.fit(ytrain)

LabelEncoder()

In [17]:
leb.classes_

array(['no', 'yes'], dtype=object)

In [18]:
ytrain

24468     no
26091     no
21143     no
9551      no
28084     no
        ...
6265      no
11284     no
38158    yes
860       no
15795     no
Name: y, Length: 10297, dtype: object

In [19]:
from sklearn.linear_model import LogisticRegression  
# 1. Create th
model = LogisticRegression()

# 2. Train the model
model.fit(xtrain, ytrain)

# 3. Predict on test data
ypred = model.predict(xtest)

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
acrr = accuracy_score(ytest,ypred)

In [22]:
acrr

0.8872487132174419

In [23]:
from sklearn.model_selection import cross_val_score

In [24]:
scores = cross_val_score(model, xtrain, ytrain, cv=5)

In [54]:
scores

array([0.88737864, 0.88737864, 0.88780962, 0.88780962, 0.88780962])