In [1]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import  train_test_split
from sklearn.preprocessing import OneHotEncoder

In [2]:
d = pd.read_csv('cars.csv')

In [3]:
d.sample(10)

         brand  km_driven    fuel         owner  selling_price
5789    Maruti      20000     CNG   First Owner         430000
3462   Hyundai     100000  Petrol  Second Owner         140000
3053    Maruti      15000  Petrol   First Owner         650000
5947     Honda      27233  Diesel   First Owner         465000
7368  Mahindra      10000  Diesel   First Owner        1450000
1171   Hyundai      31800  Petrol   First Owner         650000
6336    Maruti      65000  Petrol  Second Owner         250000
7701     Lexus      20000  Petrol   First Owner        5150000
4777  Mahindra      11500  Diesel   First Owner         819999
6855  Mahindra      19700  Petrol   First Owner         445000

In [4]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [5]:
d.value_counts('brand') # to count no of variable in a colmun

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Opel                1
Peugeot             1
Ashok               1
Name: count, dtype: int64

In [6]:
d['brand'].nunique()

32

In [7]:
d['fuel'].nunique()

4

### one hot encoding

In [9]:
pd.get_dummies(d,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

### for doing k -1  one hot encoding

In [11]:
pd.get_dummies(d,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

### One HOt encoding using sklearn

In [13]:
xtrain, xtest , ytrain, ytest = train_test_split(d.iloc[:,0:4], d.iloc[:,-1], test_size=0.3,random_state=0)

In [14]:
xtrain

           brand  km_driven    fuel         owner
5224        Tata      20000  Petrol   First Owner
520       Maruti      30000  Petrol   First Owner
36        Maruti      15000  Petrol   First Owner
5782        Ford      53000  Diesel   First Owner
6522   Chevrolet     120000  Diesel   First Owner
...          ...        ...     ...           ...
4931        Tata      70000  Diesel   Third Owner
3264        Ford     100000  Diesel  Second Owner
1653     Hyundai      90000  Petrol  Second Owner
2607  Volkswagen      90000  Diesel   First Owner
2732     Hyundai     110000  Petrol   First Owner

[5689 rows x 4 columns]

In [35]:
ohe = OneHotEncoder(drop='first', dtype=np.int32)

In [16]:
xtrainohe= ohe.fit_transform(xtrain[['fuel', 'owner']]).toarray()

In [17]:
xtestohe= ohe.fit_transform(xtest[['fuel', 'owner']]).toarray()

In [39]:
xtrainohe.shape

(5689, 7)

In [37]:
np.hstack((xtrain[['brand','km_driven']].values,xtrainohe))

array([['Tata', 20000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 30000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 15000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Hyundai', 90000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Volkswagen', 90000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 110000, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

### make categories

In [47]:
counts = d['brand'].value_counts()

In [49]:
d['brand'].nunique()
threshold = 100

In [51]:
rep = counts[counts<= threshold].index

In [53]:
pd.get_dummies(d['brand'].replace(rep,'N/A'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,N/A,Renault,Skoda,Tata,Toyota,Volkswagen
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,False,True,False,False
8127,False,False,False,False,False,False,False,False,False,False,True,False,False